### ISSUE TITLE
proposal: wget qemu tarballs instead of committing the source to the git repo

### ISSUE THREAD

**Issue by andrewrk** [ziglang/qemu-static#1]
Any reason not to do it like this?

https://github.com/ziglang/docker-zig/blob/ccffc9ab67bd7024eca340ea066710c2d644ef40/Dockerfile#L22

**Comment by mikdusan** [comment]
Ah ok I'll embed `.tar.xz` and `build` script.

**Comment by andrewrk** [comment]
Not sure I follow, are you suggesting to commit a .tar.xz to the source repo?

**Comment by andrewrk** [comment]
In this repo we could probably get by with nothing but a `do_the_thing` script that runs a docker command with another `build` script that runs inside the container and produces the .tar.xz.

**Comment by mikdusan** [comment]
https://github.com/ziglang/qemu-static/tree/redux

- moved everything into docker build process
- in order to preserve docker layering advantages, individual script-files were created for each docker step
- basically we `run container` for the sole purpose of extracting artifacts

##### [I wonder why docker doesn't have a mechanism to set `ARG` from the output of `RUN`.]

If this isn't the docker use you had in mind, let me know where responsibilities for builder ends and container begins.

**Comment by mikdusan** [comment]
`redux` branch updated to `5.0.0-rc3`

binaries: https://drive.google.com/drive/folders/12qkeNxsHHMiqDIFyAcWHMuZ45NnbC1c_?usp=sharing

**Comment by andrewrk** [comment]
Seems like you know what you're doing
